[package]
name = "media-squirrel"
version = "0.1.0"
description = "Media Squirrel - 本地媒体下载管理平台"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
strip = true
lto = true
codegen-units = 1
