<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { api } from '../api.js'
import { toast } from '../store.js'
import AppIcon from './AppIcon.vue'
import ActivityProgress from './ActivityProgress.vue'
const roots=ref([]), plans=ref([]), current=ref(null), busy=ref(false), error=ref(''), restartRequired=ref(false)
const input=reactive({source_path:'',root_id:'',copy_destination:'',backup_destination:'',backup_dir:'',restore_destination:'',source_database:'',upgrade_destination:''})
const selections=reactive({data_plan_id:'',library_plan_id:''})
let timer=null, disposed=false
const kindNames={index_only:'建立媒体索引',copy:'复制媒体目录',backup:'备份应用数据',restore:'恢复到新数据目录',upgrade_copy:'旧数据库升级副本'}
const stateNames={planned:'预检完成，等待确认',queued:'排队中',running:'执行中',success:'已完成',completed:'已完成',complete:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断',needs_replan:'源数据已变化，需要重新预检'}
const isComplete=plan=>['completed','complete','success'].includes(plan.status)
const active=computed(()=>['queued','running'].includes(current.value?.status))
const dataCandidates=computed(()=>plans.value.filter(plan=>isComplete(plan) && ['restore','upgrade_copy'].includes(plan.kind)))
const mediaCandidates=computed(()=>plans.value.filter(plan=>isComplete(plan) && plan.kind==='copy'))
const summaryLabels={files:'文件数量',bytes:'原数据容量',required_free_bytes:'所需可用空间',free_bytes:'可用空间',conflicts:'冲突',missing:'缺失文件',entries:'媒体条目',source_path:'源目录',destination:'目标目录',source_database:'源数据库',backup_dir:'备份目录',root_id:'媒体根目录标识',conflict_count:'冲突数量',missing_count:'缺失文件数量',mode:'操作方式'}
const progress=computed(()=>{const p=current.value?.progress || {};return {label:p.label || p.message || '正在处理数据',completed:p.completed ?? p.completed_files ?? p.files_done ?? p.processed,total:p.total ?? p.total_files ?? p.files_total,unit:p.unit || '项',percent:p.percent ?? (p.total_files>0?p.completed_files/p.total_files*100:null)}})
function size(value){const n=Number(value);if(!Number.isFinite(n))return value;if(n<1024)return n+' B';if(n<1024**2)return(n/1024).toFixed(1)+' KB';if(n<1024**3)return(n/1024**2).toFixed(1)+' MB';return(n/1024**3).toFixed(2)+' GB'}
function summaryValue(key,value){if(key.includes('bytes') && typeof value==='number')return size(value);if(Array.isArray(value))return value.length?value.slice(0,20).map(x=>typeof x==='object'?JSON.stringify(x):x).join('\n')+(value.length>20?`\n另有 ${value.length-20} 项`:''):'无';return typeof value==='object'?JSON.stringify(value):String(value)}
async function loadPlans(){try{const result=await api.maintenancePlans();if(!disposed)plans.value=result.items || []}catch(e){error.value=e.message}}
async function preflight(kind){busy.value=true;error.value='';try{let body={kind};if(kind==='index_only')body.source_path=input.source_path;else if(kind==='copy')Object.assign(body,{root_id:input.root_id,destination:input.copy_destination});else if(kind==='backup')body.destination=input.backup_destination;else if(kind==='restore')Object.assign(body,{backup_dir:input.backup_dir,destination:input.restore_destination});else Object.assign(body,{source_database:input.source_database,destination:input.upgrade_destination});current.value=await api.maintenancePlan(body);await loadPlans();toast('预检完成，请核对结果后确认执行','info')}catch(e){error.value=e.message}finally{busy.value=false}}
async function inspect(plan){try{current.value=await api.maintenanceStatus(plan.id)}catch(e){toast(e.message,'error')}}
async function execute(){if(!current.value)return;busy.value=true;try{const result=await api.executeMaintenance(current.value);current.value={...current.value,...result};await loadPlans()}catch(e){error.value=e.message}finally{busy.value=false}}
async function cancel(){try{await api.cancelMaintenance(current.value.id);current.value=await api.maintenanceStatus(current.value.id);await loadPlans()}catch(e){error.value=e.message}}
async function poll(){if(!active.value)return;try{const result=await api.maintenanceStatus(current.value.id);if(disposed)return;current.value=result;if(!active.value)await loadPlans()}catch(e){error.value=e.message}}
async function apply(){const body=Object.fromEntries(Object.entries(selections).filter(([,value])=>value));if(!Object.keys(body).length)return;if(!window.confirm('将所选已验证副本设为下次启动的数据位置？当前服务继续使用原位置，请完成后退出并重新运行 python run.py。原数据不会删除。'))return;busy.value=true;try{const result=await api.applyPaths(body);restartRequired.value=!!result.restart_required;toast('已保存下次启动路径，请退出服务后重新启动','success')}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(async()=>{try{const result=await api.libraryRoots();roots.value=result.items;input.root_id=result.default_root_id || roots.value[0]?.id || ''}catch(e){error.value=e.message}await loadPlans();timer=setInterval(poll,2000)})
onBeforeUnmount(()=>{disposed=true;clearInterval(timer)})
</script>
<template>
  <section class="card maintenance"><h2><AppIcon name="folder"/>媒体导入、迁移与备份</h2><p class="hint">先预检，再确认执行。复制和恢复只写入新目录；不会删除原文件或覆盖当前数据库。</p>
    <div class="operations-grid"><form @submit.prevent="preflight('index_only')"><h3>已有媒体建立索引</h3><p>只读取文件目录、context.md 和 entry.json，原文件保持原位。</p><label>已有媒体根目录<input v-model="input.source_path" class="input" required placeholder="媒体文件夹绝对路径"></label><button class="btn btn-ghost btn-sm" :disabled="busy">预检索引</button></form><form @submit.prevent="preflight('copy')"><h3>更换磁盘或媒体位置</h3><p>复制到新目录并验证结果；之后可明确切换路径，原目录继续保留。</p><label>源媒体目录<select v-model="input.root_id" class="select" required><option v-for="root in roots" :key="root.id" :value="root.id">{{ root.label }}</option></select></label><label>新的目标目录<input v-model="input.copy_destination" class="input" required placeholder="新的媒体目录绝对路径"></label><button class="btn btn-ghost btn-sm" :disabled="busy">预检复制</button></form><form @submit.prevent="preflight('backup')"><h3>备份应用数据</h3><p>包含数据库、日志和设置；不包含 Cookie、浏览器登录态、缓存和媒体原件。</p><label>备份目标目录<input v-model="input.backup_destination" class="input" required placeholder="新的备份目录绝对路径"></label><button class="btn btn-ghost btn-sm" :disabled="busy">预检备份</button></form><form @submit.prevent="preflight('restore')"><h3>从备份恢复到新目录</h3><p>验证备份并恢复到独立位置，完成后可选择下次启动使用。</p><label>备份目录<input v-model="input.backup_dir" class="input" required placeholder="已有备份目录"></label><label>新的应用数据目录<input v-model="input.restore_destination" class="input" required placeholder="新的数据目录绝对路径"></label><button class="btn btn-ghost btn-sm" :disabled="busy">预检恢复</button></form><form @submit.prevent="preflight('upgrade_copy')"><h3>旧数据库结构升级副本</h3><p>从旧安装版或其他数据位置复制数据库，在副本上执行结构升级。</p><label>旧数据库文件<input v-model="input.source_database" class="input" required placeholder="已有 .db 文件的绝对路径"></label><label>新的应用数据目录<input v-model="input.upgrade_destination" class="input" required placeholder="新的数据目录绝对路径"></label><button class="btn btn-ghost btn-sm" :disabled="busy">预检升级副本</button></form></div>
    <p v-if="error" class="maintenance-error" role="alert">{{ error }}</p>
    <section v-if="current" class="plan-review" aria-label="数据操作预检结果"><h3>{{ kindNames[current.kind] }} · {{ stateNames[current.status] || current.status }}</h3><p class="hint">计划 {{ current.id }}</p><dl><dt>源位置</dt><dd>{{ current.source_path }}</dd><dt v-if="current.destination">目标位置</dt><dd v-if="current.destination">{{ current.destination }}</dd><template v-for="(value,key) in current.summary" :key="key"><dt>{{ summaryLabels[key] || key }}</dt><dd>{{ summaryValue(key,value) }}</dd></template></dl><ActivityProgress v-if="active" :status="current.status" :progress="progress" label="数据操作进度"/><p v-if="current.error" class="maintenance-error">{{ current.error }}</p><p v-if="current.result" class="hint">结果目录：{{ current.result.prepared_data_dir || current.result.prepared_library_root || current.result.backup_dir || '索引已建立，原文件保持原位' }}</p><div class="review-actions"><button v-if="['planned','cancelled','interrupted','failed'].includes(current.status)" class="btn btn-primary btn-sm" :disabled="busy || !!current.summary?.conflict_count || !!current.summary?.missing_count" @click="execute">{{ current.status==='planned'?'确认执行此计划':'从已保存进度继续' }}</button><button v-if="active" class="btn btn-danger-ghost btn-sm" @click="cancel">取消操作</button></div><p class="hint">取消不会删除原数据。恢复执行前仍会验证计划和目标目录。</p></section>
    <details v-if="plans.length" class="plans-history"><summary>数据操作记录（{{ plans.length }}）</summary><button v-for="plan in plans" :key="plan.id" class="plan-item" @click="inspect(plan)"><span>{{ kindNames[plan.kind] || plan.kind }}</span><span>{{ stateNames[plan.status] || plan.status }}</span><small>{{ plan.id }}</small></button></details>
    <section v-if="dataCandidates.length || mediaCandidates.length" class="apply-paths"><h3>选择下次启动的数据位置</h3><p class="hint">这里只列出已经完成的副本或恢复结果。当前服务继续使用原路径，退出后重新运行才会生效。</p><div class="operations-grid"><label>应用数据副本<select v-model="selections.data_plan_id" class="select"><option value="">保持当前位置</option><option v-for="plan in dataCandidates" :key="plan.id" :value="plan.id">{{ kindNames[plan.kind] }} · {{ plan.result?.prepared_data_dir || plan.result?.prepared_library_root || plan.destination || plan.id }}</option></select></label><label>媒体目录副本<select v-model="selections.library_plan_id" class="select"><option value="">保持当前位置</option><option v-for="plan in mediaCandidates" :key="plan.id" :value="plan.id">{{ plan.result?.prepared_data_dir || plan.result?.prepared_library_root || plan.destination || plan.id }}</option></select></label></div><button class="btn btn-ghost btn-sm" :disabled="busy || (!selections.data_plan_id && !selections.library_plan_id)" @click="apply">确认下次启动使用所选路径</button><p v-if="restartRequired" class="restart-note" role="status">路径已保存。请退出后台服务并重新运行 python run.py；当前进程仍使用原数据。</p></section>
  </section>
</template>
<style scoped>
.maintenance { margin-bottom:22px; }.maintenance h2 { display:flex; gap:10px; align-items:center; font-size:18px; margin-bottom:18px; }.maintenance h3 { font-size:14px; margin-bottom:10px; }.hint { font-size:12px; color:var(--text-2); line-height:1.7; margin:10px 0 18px; overflow-wrap:anywhere; }.operations-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:18px; }.operations-grid form { background:#f0f3f5; padding:18px; border-radius:14px; }.operations-grid form p { font-size:12px; line-height:1.7; color:var(--text-2); margin-bottom:16px; }.operations-grid label { display:block; font-size:12px; color:var(--text-2); margin-bottom:12px; }.operations-grid input,.operations-grid select { margin-top:6px; font-size:12px; }.plan-review { border:1px solid #bbd2df; background:#f1f7fa; border-radius:14px; padding:20px; margin-top:22px; }.plan-review dl { display:grid; grid-template-columns:auto minmax(0,1fr); gap:9px 15px; font-size:12px; line-height:1.7; }.plan-review dt { color:var(--text-2); }.plan-review dd { white-space:pre-wrap; overflow-wrap:anywhere; }.review-actions { display:flex; gap:10px; margin-top:18px; }.maintenance-error { color:#b23d32; margin:15px 0; font-size:13px; line-height:1.7; overflow-wrap:anywhere; }.plans-history { margin-top:24px; font-size:13px; }.plans-history summary { cursor:pointer; }.plan-item { display:flex; flex-wrap:wrap; gap:10px; padding:12px 0; width:100%; background:transparent; border:0; border-bottom:1px solid var(--border); text-align:left; cursor:pointer; font-size:12px; }.plan-item small { color:var(--text-2); }.apply-paths { margin-top:24px; padding-top:20px; border-top:1px solid var(--border); }.restart-note { padding:12px; background:#fff1d9; border-radius:10px; color:#8f5c20; font-size:12px; line-height:1.7; margin-top:15px; }
@media(max-width:650px){.operations-grid { grid-template-columns:1fr; }.plan-review { padding:14px; }}
</style>
