<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from '../api.js'
import { toast } from '../store.js'
import AppIcon from './AppIcon.vue'
const props=defineProps({sub:{type:Object,required:true}})
const emit=defineEmits(['updated'])
const allSchedules=ref([]), runs=ref([]), scans=ref([]), loading=ref(false), error=ref(''), saving=ref(false), editing=ref(false), editId=ref(null), offset=ref(0), scanOffset=ref(0)
const interval=ref(props.sub.interval_minutes)
const schedules=computed(()=>allSchedules.value.filter(plan=>plan.kind!=='interval'))
const intervalPlan=computed(()=>allSchedules.value.find(plan=>plan.kind==='interval'))
const coverage=reactive({max_pages:5,max_items:200,timeout_seconds:60,overlap_hours:48})
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const draft=reactive({kind:'daily',timezone:'Asia/Shanghai',times:'09:00',start_date:today(),weekdays:[0,1,2,3,4],dates:today(),unit:'days',every:1,count:'',end_date:'',enabled:true})
const kindNames={daily:'每天',weekly:'按星期',dates:'指定日期',repeat:'周期重复'}
const dayNames=['周一','周二','周三','周四','周五','周六','周日']
const stateNames={success:'完成',partial:'覆盖不足',failed:'失败',error:'失败',queued:'排队',running:'执行中',skipped:'已合并或跳过',cancelled:'已取消',interrupted:'中断',missed:'错过',retry:'等待重试'}
const coverageReasons={network_error:'后续分页网络中断或请求超时，已取得的内容保留，请稍后重试',rate_limited:'平台请求被限流，请降低扫描频率并稍后重试',platform_error:'平台响应异常，已取得的内容保留，本轮回溯未完成',login_required:'平台限制后续分页，请登录微博后重新扫描',platform_limited:'平台限制后续分页，已取得的内容保留，请稍后重试',baseline_window:'已读取首次基线当前页',platform_end:'平台返回已到内容末尾',overlap_covered:'已覆盖设定的重叠回溯窗口',page_limit:'已达到本轮最大页数',item_limit:'已达到本轮最大条目数',time_limit:'已达到本轮扫描时间上限',pagination_stalled:'分页未取得新内容，可能受到平台限制或页面变化影响',legacy_scanner:'旧扫描器返回结果，未记录分页覆盖细节'}
function coverageText(value){if(!value || typeof value.complete!=='boolean')return '覆盖情况：此记录未保存覆盖信息';const title=value.complete?'已覆盖本轮扫描目标':'覆盖不足';const reason=coverageReasons[value.reason] || (value.reason?'扫描器说明：'+value.reason:'未提供具体原因');const counts=[Number.isFinite(value.pages)?`${value.pages} 页`:'',Number.isFinite(value.items)?`${value.items} 条`:''].filter(Boolean);return `${title}：${reason}${counts.length?' · '+counts.join(' / '):''}`}
function format(value,zone='Asia/Shanghai'){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('zh-CN',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(date)}
function items(result){return Array.isArray(result)?result:result.items || []}
async function load(){loading.value=true;error.value='';const results=await Promise.allSettled([api.subSchedules(props.sub.id),api.scheduleRuns(props.sub.id,offset.value),api.subScans(props.sub.id,scanOffset.value)]);if(results[0].status==='fulfilled')allSchedules.value=items(results[0].value).map(item=>({...item.plan,...item}));else error.value=results[0].reason.message;if(results[1].status==='fulfilled')runs.value=items(results[1].value);if(results[2].status==='fulfilled')scans.value=items(results[2].value);loading.value=false}
function edit(schedule){editId.value=schedule?.id || null;Object.assign(draft,{kind:schedule?.kind || 'daily',timezone:schedule?.timezone || 'Asia/Shanghai',times:(schedule?.times || ['09:00']).join(', '),start_date:schedule?.start_date || today(),weekdays:[...(schedule?.weekdays || [0,1,2,3,4])],dates:(schedule?.dates || [today()]).join('\n'),unit:schedule?.unit || 'days',every:schedule?.every || 1,count:schedule?.count || '',end_date:schedule?.end_date || '',enabled:schedule?.enabled ?? true});editing.value=true}
function description(plan){const parts=[kindNames[plan.kind] || plan.kind];if(plan.kind==='weekly')parts.push((plan.weekdays || []).map(day=>dayNames[day]).join('、'));if(plan.kind==='dates')parts.push((plan.dates || []).join('、'));if(plan.kind==='repeat')parts.push(`每 ${plan.every} ${{days:'天',weeks:'周',months:'月'}[plan.unit] || plan.unit}`);parts.push((plan.times || []).join(' / '));return parts.join(' · ')}
async function save(){saving.value=true;try{const body={...draft,times:[...new Set(draft.times.split(/[,，\s]+/).filter(Boolean))],dates:[...new Set(draft.dates.split(/[,，\s]+/).filter(Boolean))],weekdays:[...draft.weekdays].sort(),count:draft.count?Number(draft.count):null,end_date:draft.end_date || null,every:Number(draft.every),enabled:!!draft.enabled};if(!body.times.length || body.times.some(time=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)))throw new Error('请用 HH:mm 填写时间，多个时间用逗号分隔。');if(body.kind==='weekly' && !body.weekdays.length)throw new Error('请至少选择一个星期。');if(editId.value)await api.updateSchedule(editId.value,body);else await api.addSchedule(props.sub.id,body);editing.value=false;await load();toast('扫描计划已保存','success');emit('updated')}catch(e){toast(e.message,'error')}finally{saving.value=false}}
async function toggle(plan){try{await api.updateSchedule(plan.id,{...plan.plan,enabled:!plan.enabled});await load()}catch(e){toast(e.message,'error')}}
async function remove(plan){if(!window.confirm('删除这个固定时间计划？订阅、扫描记录和媒体文件都会保留。'))return;try{await api.removeSchedule(plan.id);await load()}catch(e){toast(e.message,'error')}}
async function saveInterval(){try{if(!Number.isFinite(Number(interval.value)) || interval.value<5)throw new Error('扫描间隔至少 5 分钟。');await api.updateSub(props.sub.id,{interval_minutes:Number(interval.value)});emit('updated');toast('间隔已更新，固定时间计划保持独立','success')}catch(e){toast(e.message,'error')}}
async function pageRuns(delta){offset.value=Math.max(0,offset.value+delta*20);await load()}
async function pageScans(delta){scanOffset.value=Math.max(0,scanOffset.value+delta*20);await load()}
async function saveCoverage(){try{const body=Object.fromEntries(['max_pages','max_items','timeout_seconds','overlap_hours'].map(key=>[key,Number(coverage[key])]))
await api.saveScanOptions(props.sub.id,body);toast('扫描覆盖参数已保存','success')}catch(e){toast(e.message,'error')}}
onMounted(()=>{load();api.scanOptions(props.sub.id).then(result=>Object.assign(coverage,result)).catch(()=>{})})
</script>
<template>
  <section class="schedule-panel">
    <div class="interval-row"><label>间隔扫描 <input v-model.number="interval" class="input" type="number" min="5"> 分钟</label><button class="btn btn-ghost btn-sm" @click="saveInterval">保存间隔</button><button v-if="intervalPlan" class="text-button" @click="toggle(intervalPlan)">{{ intervalPlan.enabled?'暂停间隔扫描':'启用间隔扫描' }}</button><span v-if="intervalPlan" class="schedule-hint">下次 {{ format(intervalPlan.next_due, intervalPlan.timezone) }}</span></div>
    <div class="schedule-heading"><h3><AppIcon name="calendar" :size="20"/>固定时间计划</h3><button class="btn btn-ghost btn-sm" @click="edit(null)">添加计划</button></div>
    <p class="schedule-hint">应用运行时执行。间隔、计划与手动扫描相互独立，同一订阅重叠时合并；休眠或退出期间无法执行。首次扫描只建立基线。</p>
    <p v-if="loading" role="status" class="schedule-hint">正在读取计划与扫描记录…</p><p v-if="error" class="error-text" role="alert">{{ error }}</p>
    <p v-if="!loading && !schedules.length" class="schedule-hint">尚未添加固定时间计划。</p>
    <article v-for="plan in schedules" :key="plan.id" class="schedule-item"><div><strong>{{ description(plan) }}</strong><p>{{ plan.timezone }} · {{ plan.enabled?'启用':'暂停' }} · 下次 {{ format(plan.next_due,plan.timezone) }}</p><p v-if="plan.retry_due">重试时间 {{ format(plan.retry_due,plan.timezone) }}</p><p v-if="plan.last_status">上次：{{ stateNames[plan.last_status] || plan.last_status }}<span v-if="plan.last_error" class="error-text"> · {{ plan.last_error }}</span></p></div><div class="schedule-actions"><button class="text-button" @click="edit(plan)">编辑</button><button class="text-button" @click="toggle(plan)">{{ plan.enabled?'暂停':'启用' }}</button><button class="text-button" @click="remove(plan)">删除</button></div></article>
    <form v-if="editing" class="schedule-editor" @submit.prevent="save"><h4>{{ editId?'编辑计划':'新增计划' }}</h4><div class="editor-grid"><label>重复方式<select v-model="draft.kind" class="select"><option v-for="(label,key) in kindNames" :key="key" :value="key">{{ label }}</option></select></label><label>时区<input v-model="draft.timezone" class="input" required placeholder="Asia/Shanghai"></label><label>执行时间<input v-model="draft.times" class="input" required placeholder="09:00, 18:00"></label><label>开始日期<input v-model="draft.start_date" class="input" type="date" required></label></div><div v-if="draft.kind==='weekly'" class="weekday-row"><label v-for="(label,index) in dayNames" :key="index"><input v-model="draft.weekdays" type="checkbox" :value="index"> {{ label }}</label></div><label v-if="draft.kind==='dates'" class="date-list">指定日期（每行一个 YYYY-MM-DD）<textarea v-model="draft.dates" class="textarea" required></textarea></label><div v-if="draft.kind==='repeat'" class="editor-grid"><label>每隔<input v-model.number="draft.every" type="number" min="1" class="input" required></label><label>单位<select v-model="draft.unit" class="select"><option value="days">天</option><option value="weeks">周</option><option value="months">月</option></select></label></div><p v-if="draft.kind==='repeat' && draft.unit==='months'" class="schedule-hint">以开始日期的日号重复，较短月份使用该月最后一天。</p><div class="editor-grid"><label>执行次数上限（可留空）<input v-model.number="draft.count" class="input" type="number" min="1"></label><label>结束日期（可留空）<input v-model="draft.end_date" class="input" type="date"></label></div><p class="schedule-hint">次数按计划时点计算，包含错过后合并的时点。可只填一个指定日期和一个时间安排一次执行。</p><div class="schedule-actions"><button class="btn btn-primary btn-sm" :disabled="saving">{{ saving?'保存中…':'保存计划' }}</button><button type="button" class="btn btn-ghost btn-sm" @click="editing=false">取消</button></div></form>
    <details class="record-section"><summary>扫描覆盖范围</summary><p class="schedule-hint">达到页数、条数、超时或平台限制时可能未覆盖全部历史；增加计划频率不能保证不漏抓。已成功内容不会因本地删除而自动重下。</p><form @submit.prevent="saveCoverage"><div class="editor-grid"><label>每轮最多页数<input v-model.number="coverage.max_pages" class="input" type="number" min="1" max="20"></label><label>每轮最多条目<input v-model.number="coverage.max_items" class="input" type="number" min="1" max="2000"></label><label>扫描超时（秒）<input v-model.number="coverage.timeout_seconds" class="input" type="number" min="10" max="180"></label><label>重叠回溯窗口（小时）<input v-model.number="coverage.overlap_hours" class="input" type="number" min="1" max="720"></label></div><p class="schedule-hint">{{ coverage.baseline?'尚未建立首次基线。':'下次回溯起点：'+format(coverage.cutoff_at) }}</p><button class="btn btn-ghost btn-sm">保存覆盖参数</button></form></details>
    <details class="record-section"><summary>计划执行记录（Asia/Shanghai）</summary><p v-if="!runs.length" class="schedule-hint">暂无计划执行记录。</p><div v-for="run in runs" :key="run.id" class="record-row"><strong>{{ format(run.due_at || run.scheduled_at || run.started_at) }} · {{ stateNames[run.status] || run.status }}</strong><p v-if="run.reason || run.error">{{ run.reason || run.error }}</p><p :class="{'coverage-warning':run.coverage?.complete===false}">{{ coverageText(run.coverage) }}</p></div><div class="record-pages"><button class="text-button" :disabled="offset===0" @click="pageRuns(-1)">上一页</button><span>第 {{ offset/20+1 }} 页</span><button class="text-button" :disabled="runs.length<20" @click="pageRuns(1)">下一页</button></div></details>
    <details class="record-section"><summary>全部扫描结果记录（Asia/Shanghai）</summary><p v-if="!scans.length" class="schedule-hint">暂无扫描记录。</p><div v-for="item in scans" :key="item.id" class="record-row"><strong>{{ format(item.started_at) }} · {{ stateNames[item.status] || item.status }}</strong><p>{{ item.error || item.summary || item.trigger || '扫描记录已保留' }}</p><p>扫描到 {{ item.items_count || 0 }} 条 · 本轮候选 {{ item.new_count || 0 }} 条<span v-if="item.baseline"> · 首次基线</span></p><p :class="{'coverage-warning':item.coverage?.complete===false}">{{ coverageText(item.coverage) }}</p></div><div class="record-pages"><button class="text-button" :disabled="scanOffset===0" @click="pageScans(-1)">上一页</button><span>第 {{ scanOffset/20+1 }} 页</span><button class="text-button" :disabled="scans.length<20" @click="pageScans(1)">下一页</button></div></details>
  </section>
</template>
<style scoped>
.schedule-panel { margin-top:18px; padding-top:20px; border-top:1px solid var(--border); }.interval-row { display:flex; flex-wrap:wrap; align-items:center; gap:12px; margin-bottom:20px; font-size:13px; }.interval-row label { display:flex; align-items:center; gap:8px; }.interval-row input { width:95px; padding:8px; }.schedule-heading { display:flex; justify-content:space-between; gap:12px; align-items:center; }.schedule-heading h3 { font-size:14px; display:flex; align-items:center; gap:8px; }.schedule-hint { font-size:12px; color:var(--text-2); line-height:1.7; margin:10px 0; }.schedule-item { display:flex; align-items:flex-start; justify-content:space-between; gap:12px; padding:12px 0; border-bottom:1px solid var(--border); font-size:12px; line-height:1.7; }.schedule-item strong { font-size:13px; }.schedule-item p { color:var(--text-2); }.schedule-actions { display:flex; flex-wrap:wrap; gap:8px; }.text-button { border:0; background:transparent; color:var(--blue); cursor:pointer; padding:3px 5px; font-size:12px; white-space:nowrap; }.text-button:disabled { opacity:.4; }.schedule-editor { background:#eef3f5; border-radius:12px; padding:18px; margin:18px 0; }.schedule-editor h4 { margin-bottom:15px; }.editor-grid { display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-bottom:15px; }.editor-grid label,.date-list { font-size:12px; color:var(--text-2); }.editor-grid input,.editor-grid select,.date-list textarea { margin-top:6px; font-size:13px; }.weekday-row { display:flex; flex-wrap:wrap; gap:12px; margin:18px 0; font-size:12px; }.record-section { margin-top:18px; font-size:13px; }.record-section summary { cursor:pointer; }.record-row { font-size:12px; line-height:1.7; padding:12px 0; border-bottom:1px solid var(--border); overflow-wrap:anywhere; }.record-row p { color:var(--text-2); }.record-pages { display:flex; gap:12px; font-size:12px; align-items:center; margin-top:10px; }.error-text { color:#b53930; }
.record-row .coverage-warning { color:#9b572e; }
@media(max-width:600px){.schedule-item { flex-wrap:wrap; }.editor-grid { grid-template-columns:1fr; }.schedule-editor { padding:14px; }}
</style>
