<script setup>
import { onMounted, reactive, ref } from 'vue'
import { api } from '../api.js'
import { toast, upsertTaskSummary, store } from '../store.js'
import AppIcon from '../components/AppIcon.vue'
import MaintenancePanel from '../components/MaintenancePanel.vue'
const settings=ref(null), loading=ref(true), saving=ref(false), busy=ref(''), error=ref(''), checks=ref([]), browserChecks=ref([]), diagnosticUrl=ref(''), testTask=ref(null)
const values=reactive({default_download_dir:'',download_concurrency:1,timeout_seconds:120,retries:2,cache_limit_mb:2048,notifications:'in_app',density:'comfortable',reduce_motion:true})
const test=reactive({script_id:'weibo',input:''})
const labels={passed:'通过',unverified:'未验证',not_run:'未检测',pass:'通过',ok:'通过',success:'通过',fail:'失败',failed:'失败',error:'失败',warning:'需处理',warn:'需处理',unknown:'未确认',unavailable:'不可用',skipped:'未检测',not_tested:'未检测'}
function formatBytes(value){if(value===undefined || value===null)return '暂不可用';const bytes=Math.max(0,Number(value)||0);if(bytes<1024)return `${bytes} B`;const units=['KiB','MiB','GiB','TiB'];const index=Math.min(Math.floor(Math.log(bytes)/Math.log(1024))-1,units.length-1);return `${(bytes/1024**(index+1)).toFixed(1)} ${units[index]}`}
async function load(){loading.value=true;error.value='';try{settings.value=await api.settings();Object.assign(values,settings.value.values || {});store.preferences={...values}}catch(e){error.value=e.message}finally{loading.value=false}}
async function save(){saving.value=true;try{const result=await api.saveSettings({...values,reduce_motion:true,notifications:'in_app'});settings.value={...settings.value,...result};store.preferences={...values};await load();toast('设置已保存','success')}catch(e){toast(e.message,'error')}finally{saving.value=false}}
async function diagnose(browser=false){busy.value=browser?'browser':'diagnostics';try{const result=await (browser?api.checkBrowser():api.diagnostics());if(browser)browserChecks.value=result.checks || [];else checks.value=result.checks || []}catch(e){toast(e.message,'error')}finally{busy.value=''}}
async function exportDiagnostics(){busy.value='export';try{const result=await api.exportDiagnostics();diagnosticUrl.value=result.download_url;toast('脱敏诊断文件已生成','success')}catch(e){toast(e.message,'error')}finally{busy.value=''}}
async function realCheck(){if(!test.input.trim())return;if(!window.confirm('使用填写的链接进行真实联网下载检测？输出将保存在独立诊断目录，不加入正常媒体库。'))return;busy.value='download';try{const input=test.script_id==='weibo'?(test.input.match(/https?:\/\/[^\s<>"，。！？）)]+/i)?.[0] || test.input):test.input;const result=await api.checkDownload({...test,input,confirmed:true});testTask.value=result.task || result;if(testTask.value.id)upsertTaskSummary(testTask.value);toast('已创建独立下载检测任务，可查看任务日志','success')}catch(e){toast(e.message,'error')}finally{busy.value=''}}
onMounted(()=>{const content=document.querySelector('.content');if(content)content.scrollTop=0;load()})
</script>
<template>
  <div class="settings-view"><h1 class="page-title">设置</h1><p class="page-sub">运行环境、存储位置和本地数据管理。</p>
    <p v-if="loading" role="status">正在读取设置…</p><div v-if="error" class="card error-text" role="alert">{{ error }} <button class="btn btn-ghost btn-sm" @click="load">重试</button></div>
    <template v-if="settings">
      <section class="card settings-card"><h2><AppIcon name="folder"/>数据位置</h2><dl class="path-list"><dt>媒体库</dt><dd>{{ settings.paths?.library_root }}</dd><dt>默认下载目录</dt><dd>{{ settings.paths?.default_download_dir || settings.paths?.library_root }}</dd><dt>应用数据</dt><dd>{{ settings.paths?.data_dir }}</dd></dl><p class="hint">媒体原文件保存在项目目录之外。更改路径需要先预检并明确选择索引或迁移方式。</p><details v-if="settings.paths?.legacy_locations?.length"><summary>旧版数据位置</summary><ul><li v-for="(location,index) in settings.paths.legacy_locations" :key="index"><template v-if="typeof location==='string'">{{ location }}</template><template v-else><strong>{{ location.kind==='source'?'旧源码版':'旧桌面版' }}</strong><p>应用数据：{{ location.data_dir }}（{{ location.database_exists?'存在数据库':'未找到数据库' }}）</p><p>媒体目录：{{ location.library_root }}</p></template></li></ul></details></section>
      <MaintenancePanel/>
      <section class="card settings-card"><h2><AppIcon name="settings"/>日常运行</h2><form @submit.prevent="save"><div class="settings-grid"><label>默认下载子目录（绝对路径，可留空）<input v-model="values.default_download_dir" class="input" placeholder="留空使用当前媒体库根目录"></label><label>同时下载任务数<input v-model.number="values.download_concurrency" class="input" type="number" min="1" max="4" required></label><label>网络请求超时（秒）<input v-model.number="values.timeout_seconds" class="input" type="number" min="10" max="600" required></label><label>失败重试次数<input v-model.number="values.retries" class="input" type="number" min="0" max="5" required></label><label>缩略图缓存目标容量（MB）<input v-model.number="values.cache_limit_mb" class="input" type="number" min="128" max="32768" required></label><label>列表密度<select v-model="values.density" class="select"><option value="comfortable">舒适</option><option value="compact">紧凑</option></select></label></div><p class="hint">默认下载子目录必须位于当前媒体库内；换磁盘请使用上方预检。通知使用应用内弹出提示。图标与页面保持静止，只有任务进度条显示进度动画。关闭浏览器后后台服务可继续工作，页面提示需重新打开后查看。</p><button class="btn btn-primary" :disabled="saving">{{ saving?'保存中…':'保存设置' }}</button></form></section>
      <section class="card settings-card"><h2><AppIcon name="tasks"/>任务与日志保留</h2><p>任务摘要长期保留；详细日志长期保存并压缩归档。隐藏任务、删除详细日志与删除媒体是独立操作。</p><p class="hint">本轮不按天数或条数自动删除任务和日志。任务页可显示隐藏记录并恢复。</p><dl v-if="settings.storage" class="version-list"><dt>任务记录（含隐藏）</dt><dd>{{ settings.storage.task_count ?? '暂不可用' }}</dd><dt>数据库（含事务日志）</dt><dd>{{ formatBytes(settings.storage.database_bytes) }}</dd><dt>已归档详细日志</dt><dd>{{ formatBytes(settings.storage.archived_log_bytes) }}</dd><dt>数据磁盘剩余空间</dt><dd>{{ formatBytes(settings.storage.free_bytes) }}</dd></dl><p v-if="settings.storage?.low_space" role="alert" class="error-text">数据磁盘剩余空间不足 512 MiB。建议将备份保存到空间充足的位置，并在确认后手动清理不再需要的日志；应用不会自动删除数据。</p><p v-if="settings.storage" class="hint">容量统计最多缓存 60 秒。缩略图容量为清理目标；最近 10 分钟使用的缓存受到保护，可能暂时超过目标。</p><router-link to="/tasks" class="btn btn-ghost btn-sm">管理任务与日志</router-link></section>
      <section class="card settings-card"><h2><AppIcon name="scan"/>环境与脚本检测</h2><p class="hint">依赖检查、浏览器启动和登录态检查分别显示。只有使用你确认的链接完成实际下载，才能验证平台当前可用性。</p><div class="settings-actions"><button class="btn btn-ghost" :disabled="!!busy" @click="diagnose(false)">检查依赖与登录态</button><button class="btn btn-ghost" :disabled="!!busy" @click="diagnose(true)">检测浏览器环境</button></div><p v-if="busy==='diagnostics' || busy==='browser'" role="status" class="hint">正在检测…</p><div v-for="check in [...checks,...browserChecks]" :key="check.id" class="check-row"><div><strong>{{ check.label || check.id }}</strong><p>{{ check.reason }}</p><p v-if="check.suggestion" class="hint">处理建议：{{ check.suggestion }}</p></div><span class="check-badge" :class="'check-'+check.status">{{ labels[check.status] || check.status }}</span></div>
        <form class="real-check" @submit.prevent="realCheck"><h3>真实联网下载检测</h3><p class="hint">请填写要测试的链接或分享文案；点击后再确认联网下载。检测输出进入独立诊断目录。</p><div class="settings-grid"><label>平台<select v-model="test.script_id" class="select"><option value="weibo">微博</option><option value="douyin">抖音</option></select></label><label class="test-link">测试链接 / 分享文案<input v-model="test.input" class="input" required placeholder="填写你确认使用的测试内容"></label></div><button class="btn btn-ghost" :disabled="!!busy || !test.input.trim()">{{ busy==='download'?'创建中…':'创建下载检测任务' }}</button><router-link v-if="testTask?.id" :to="{path:'/tasks',query:{task:testTask.id}}" class="text-link">查看检测任务</router-link></form>
      </section>
      <section class="card settings-card"><h2><AppIcon name="info"/>版本与脱敏诊断</h2><dl class="version-list"><template v-for="(value,key) in settings.versions" :key="key"><dt>{{ key }}</dt><dd>{{ value ?? '未安装或不可用' }}</dd></template></dl><p class="hint">诊断文件排除登录凭据并额外脱敏。下载后可先自行审阅，再决定是否分享。</p><button class="btn btn-ghost btn-sm" :disabled="!!busy" @click="exportDiagnostics">生成脱敏诊断</button><a v-if="diagnosticUrl" class="text-link" :href="diagnosticUrl" download>下载诊断文件</a><p class="hint">图标素材与许可：<a href="/licenses/README.md" target="_blank" rel="noopener">查看来源记录</a></p></section>
    </template>
  </div>
</template>
<style scoped>
.settings-card { margin-bottom:22px; }.settings-card h2 { display:flex; align-items:center; gap:10px; font-size:18px; margin-bottom:20px; }.settings-card p { font-size:13px; line-height:1.7; }.settings-card .hint { font-size:12px; color:var(--text-2); margin:12px 0 18px; }.path-list,.version-list { display:grid; grid-template-columns:auto minmax(0,1fr); gap:12px 20px; font-size:13px; line-height:1.6; }.path-list dt,.version-list dt { color:var(--text-2); }.path-list dd,.version-list dd { overflow-wrap:anywhere; }.settings-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:18px; margin-bottom:20px; }.settings-grid label { font-size:12px; color:var(--text-2); }.settings-grid input,.settings-grid select { margin-top:7px; }.settings-actions { display:flex; flex-wrap:wrap; gap:10px; margin-bottom:15px; }.check-row { display:flex; justify-content:space-between; gap:14px; border-top:1px solid var(--border); padding:15px 0; font-size:13px; }.check-row>div { flex:1; min-width:0; overflow-wrap:anywhere; }.check-row p { margin-top:7px; }.check-badge { height:max-content; border-radius:8px; background:#e8edf3; color:#647a8c; padding:4px 8px; font-size:11px; white-space:nowrap; }.check-passed,.check-pass,.check-ok,.check-success { background:#e2f0e4; color:#427951; }.check-fail,.check-failed,.check-error { background:#ffe8e2; color:#b43e35; }.real-check { margin-top:20px; padding-top:20px; border-top:1px solid var(--border); }.real-check h3 { font-size:15px; }.real-check .settings-grid { grid-template-columns:120px minmax(0,1fr); }.text-link { color:var(--blue); font-size:13px; margin-left:16px; }.error-text { color:#b23d32; }details { font-size:12px; color:var(--text-2); line-height:1.8; }details summary { cursor:pointer; }details ul { padding-left:20px; margin-top:10px; }
@media(max-width:600px){.settings-grid,.real-check .settings-grid { grid-template-columns:1fr; }.path-list { grid-template-columns:1fr; gap:5px; }.path-list dd { margin-bottom:10px; }.text-link { display:block; margin:12px 0 0; }}
</style>
