<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { api } from '../api.js'
import { store, refreshSubs, toast } from '../store.js'
import ActivityProgress from '../components/ActivityProgress.vue'
import AppIcon from '../components/AppIcon.vue'
import PlatformLogo from '../components/PlatformLogo.vue'
import Avatar from '../components/Avatar.vue'
import SchedulePanel from '../components/SchedulePanel.vue'
const loading=ref(true), adding=ref(false), searching=ref(false), onlineResults=ref([]), localAuthors=ref([]), searchOpen=ref(false), searchError=ref(''), needCaptcha=ref(false), verifying=ref(false), dyAuth=ref({logged_in:false}), activeIndex=ref(-1), scanning=reactive({}), expanded=ref(null)
const form=reactive({platform:'douyin',nickname:'',blogger_id:'',homepage:'',interval_minutes:30,avatar_url:''})
const listQuery=ref(''), listPlatform=ref(''), listState=ref('')
const platformName={douyin:'抖音',weibo:'微博'}
let debounceTimer=null, blurTimer=null, request=null, searchSequence=0, disposed=false, picking=false
const keyword=computed(()=>form.nickname.trim())
const localMatches=computed(()=>localAuthors.value.filter(item=>item.platforms?.[form.platform] && (!keyword.value || item.name.toLowerCase().includes(keyword.value.toLowerCase()))).slice(0,6))
const options=computed(()=>[...localMatches.value.map(item=>({local:true,item})),...onlineResults.value.map(item=>({local:false,item}))])
const shownSubs=computed(()=>store.subs.filter(sub=>{
  const query=listQuery.value.trim().toLowerCase()
  return (!query || [sub.nickname,sub.blogger_id,sub.homepage].some(value=>String(value || '').toLowerCase().includes(query))) && (!listPlatform.value || sub.platform===listPlatform.value) && (!listState.value || (listState.value==='enabled'?!!sub.enabled:listState.value==='paused'?!sub.enabled:['error','failed','interrupted'].includes(sub.last_status) || sub.scan?.status==='failed'))
}))
function stopSearch(){clearTimeout(debounceTimer);request?.abort();searchSequence++;searching.value=false}
watch(keyword,()=>{stopSearch();onlineResults.value=[];needCaptcha.value=false;searchError.value='';activeIndex.value=-1;if(picking){picking=false;searchOpen.value=false;return}form.blogger_id='';form.avatar_url='';searchOpen.value=!!keyword.value;if(keyword.value)debounceTimer=setTimeout(runSearch,400)})
watch(()=>form.platform,()=>{stopSearch();form.blogger_id='';form.avatar_url='';onlineResults.value=[];needCaptcha.value=false;if(keyword.value)debounceTimer=setTimeout(runSearch,400)})
async function runSearch(){if(!keyword.value)return;request?.abort();request=new AbortController();const sequence=++searchSequence;const q=keyword.value;searching.value=true;searchError.value='';try{const result=await api.searchBlogger(form.platform,q,request.signal);if(disposed || sequence!==searchSequence)return;onlineResults.value=result.results || [];needCaptcha.value=!!result.captcha_required;searchOpen.value=true}catch(e){if(sequence===searchSequence && e.name!=='AbortError')searchError.value=e.message}finally{if(sequence===searchSequence)searching.value=false}}
function pick(option){stopSearch();const item=option.item;picking=form.nickname!==(option.local?item.name:item.nickname);form.nickname=option.local?item.name:item.nickname;form.blogger_id=option.local?item.platforms[form.platform]:item.blogger_id;form.avatar_url=option.local?'':item.avatar_source || item.avatar || '';form.homepage=item.homepage || '';searchOpen.value=false;activeIndex.value=-1}
function onSearchKey(event){if(event.key==='Escape'){searchOpen.value=false;stopSearch();return}if(!searchOpen.value || !options.value.length)return;if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();activeIndex.value=(activeIndex.value+(event.key==='ArrowDown'?1:-1)+options.value.length)%options.value.length}else if(event.key==='Enter'){event.preventDefault();pick(options.value[activeIndex.value] || options.value[0])}}
function closeDropdown(){clearTimeout(blurTimer);blurTimer=setTimeout(()=>{searchOpen.value=false},150)}
function parseIdentity(value){const text=value.trim();if(!/^https?:\/\//i.test(text))return text;const url=new URL(text);if(form.platform==='weibo' && /(^|\.)weibo\.(com|cn)$/.test(url.hostname)){const match=url.pathname.match(/^\/(?:u\/)?(\d+)(?:\/|$)/);if(match){form.homepage=text;return match[1]}}if(form.platform==='douyin' && /(^|\.)douyin\.com$/.test(url.hostname)){const match=url.pathname.match(/^\/user\/([^/]+)/);if(match){form.homepage=text;return match[1]}}throw new Error('无法从此链接识别博主 ID，请使用完整博主主页或搜索结果。')}
async function refresh(){try{await refreshSubs()}catch(e){toast('订阅加载失败：'+e.message,'error')}finally{loading.value=false}}
async function add(){adding.value=true;try{const id=parseIdentity(form.blogger_id);if(!id)throw new Error('请先选择博主或填写博主 ID。');if(store.subs.some(sub=>sub.platform===form.platform && sub.blogger_id===id)){toast('该博主已经订阅，可在下方调整计划','info');return}await api.addSub({...form,blogger_id:id});toast('订阅已添加，首次扫描只建立基线','success');picking=true;form.nickname='';form.blogger_id='';form.homepage='';form.avatar_url='';searchOpen.value=false;await refresh()}catch(e){toast(e.message,'error')}finally{adding.value=false}}
async function toggle(sub){try{await api.updateSub(sub.id,{enabled:sub.enabled?0:1});await refresh()}catch(e){toast(e.message,'error')}}
async function remove(sub){if(!window.confirm(`删除订阅「${sub.nickname || sub.blogger_id}」？已下载媒体与任务记录仍会保留。`))return;try{await api.removeSub(sub.id);await refresh();toast('订阅已删除','info')}catch(e){toast(e.message,'error')}}
function isScanning(sub){return scanning[sub.id] || sub.scan?.status==='running'}
function scanState(sub){return scanning[sub.id] && sub.scan?.status!=='running'?{status:'running',progress:{label:'正在准备扫描…',percent:null}}:sub.scan}
async function scanNow(sub){if(isScanning(sub))return;scanning[sub.id]=true;try{const result=await api.scanSub(sub.id);if(result.already_running)toast('此订阅已有扫描在运行','info');else if(result.error)toast('扫描失败：'+result.error,'error');else if(result.baseline!=null)toast(`已建立基线，共 ${result.baseline} 条内容`,'success');else toast(result.new_items?.length?`发现 ${result.new_items.length} 条内容，入队结果可从记录查看`:'扫描完成，暂无新增内容','info')}catch(e){toast(e.message,'error')}finally{delete scanning[sub.id];await refresh()}}
async function loadAuth(){try{dyAuth.value=await api.douyinAuth()}catch{}}
async function login(){verifying.value=true;try{const result=await api.loginDouyin();if(!result.ok)throw new Error(result.detail || '登录验证未完成，请重试。');await loadAuth();toast(result.logged_in?'登录成功，登录态保存在本机':'验证完成，尚未检测到登录','info');if(keyword.value)runSearch()}catch(e){toast(e.message,'error')}finally{verifying.value=false}}
function time(value){if(!value)return '尚未扫描';const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('zh-CN',{dateStyle:'short',timeStyle:'short',hour12:false}).format(date)}
onMounted(()=>{const content=document.querySelector('.content');if(content)content.scrollTop=0;refresh();loadAuth();api.localAuthors().then(result=>{if(!disposed)localAuthors.value=result}).catch(()=>{})})
onBeforeUnmount(()=>{disposed=true;stopSearch();clearTimeout(blurTimer)})
</script>
<template>
  <div class="subscriptions-view"><h1 class="page-title">博主订阅</h1><p class="page-sub">按间隔或指定时间发现新内容，扫描与下载结果分别保留。</p>
    <section class="card add-card"><div class="add-heading"><h2>添加订阅</h2><div class="auth-status"><span>{{ dyAuth.logged_in?'抖音登录态已保存':'尚未检测到抖音登录态' }}</span><button class="btn btn-ghost btn-sm" :disabled="verifying" @click="login">{{ verifying?'等待验证…':dyAuth.logged_in?'重新登录':'登录抖音' }}</button></div></div>
      <form @submit.prevent="add"><div class="add-grid"><label>平台<select v-model="form.platform" class="select"><option value="douyin">抖音</option><option value="weibo">微博</option></select></label><label class="search-field">搜索平台博主<div class="search-box"><input v-model="form.nickname" class="input" placeholder="输入昵称，选中结果后添加" autocomplete="off" role="combobox" :aria-expanded="searchOpen" aria-controls="blogger-results" @focus="searchOpen=true" @blur="closeDropdown" @keydown="onSearchKey"><button v-if="searching" type="button" class="cancel-search" @click="stopSearch">取消搜索</button><div v-if="searchOpen && keyword" id="blogger-results" class="search-drop" role="listbox"><p class="drop-section">本地作者与 {{ platformName[form.platform] }} 搜索结果</p><button v-for="(option,index) in options" :key="(option.local?'local:':'online:')+(option.item.blogger_id || option.item.name)" type="button" class="drop-item" :class="{active:activeIndex===index}" role="option" :aria-selected="activeIndex===index" @mousedown.prevent="pick(option)"><Avatar :src="option.item.avatar_url || option.item.avatar" :name="option.item.nickname || option.item.name" :size="32"/><span>{{ option.item.nickname || option.item.name }}<small>{{ option.local?'本地存档':option.item.followers_text || '平台博主' }}</small></span></button><p v-if="searching" class="drop-message">正在搜索…</p><p v-else-if="searchError" class="drop-message error-text">{{ searchError }}</p><p v-else-if="!options.length && !needCaptcha" class="drop-message">没有匹配结果。也可以直接填写博主 ID 或主页。</p><div v-if="needCaptcha" class="captcha-notice"><p>平台要求验证或登录。点击后会打开浏览器窗口，登录态仅保存本机。</p><button type="button" class="btn btn-ghost btn-sm" :disabled="verifying" @mousedown.prevent @click="login">打开登录窗口</button></div></div></div></label><label>博主 ID / 完整主页<input v-model="form.blogger_id" class="input" required :placeholder="form.platform==='weibo'?'微博 UID 或主页链接':'抖音 sec_uid 或完整主页'"></label><label>间隔（分钟）<input v-model.number="form.interval_minutes" class="input" type="number" min="5" required></label></div><button class="btn btn-primary" :disabled="adding">{{ adding?'添加中…':'添加订阅' }}</button><p class="add-hint">首次扫描建立基线，不自动下载全部历史内容。固定时间计划可在添加后设置。</p></form>
    </section>
    <div class="list-filters"><input v-model="listQuery" class="input" type="search" aria-label="筛选已有订阅" placeholder="筛选已有订阅：昵称、ID 或主页"><select v-model="listPlatform" class="select" aria-label="筛选订阅平台"><option value="">全部平台</option><option value="weibo">微博</option><option value="douyin">抖音</option></select><select v-model="listState" class="select" aria-label="筛选订阅状态"><option value="">全部状态</option><option value="enabled">已启用</option><option value="paused">已暂停</option><option value="error">上次出错</option></select></div>
    <div v-if="loading" class="card empty"><AppIcon name="subs" :size="60"/><p>正在读取订阅…</p></div><div v-else-if="!shownSubs.length" class="card empty"><AppIcon name="subs" :size="60"/><p>{{ store.subs.length?'没有符合筛选条件的订阅':'还没有订阅博主' }}</p></div>
    <div v-else class="sub-list"><article v-for="sub in shownSubs" :key="sub.id" class="card sub-card"><div class="sub-head"><Avatar :src="sub.avatar_url || sub.avatar" :name="sub.nickname"/><div class="sub-info"><h2><PlatformLogo :platform="sub.platform" :size="22"/>{{ sub.nickname || sub.blogger_id }}</h2><p>{{ sub.blogger_id }}</p><p>每 {{ sub.interval_minutes }} 分钟 · 上次 {{ time(sub.last_scan_at) }}<span v-if="sub.last_status"> · {{ {ok:'完成',success:'完成',error:'失败',failed:'失败',baseline:'基线已建立'}[sub.last_status] || sub.last_status }}</span></p></div><label class="switch"><input type="checkbox" :checked="!!sub.enabled" :aria-label="`启用 ${sub.nickname || sub.blogger_id} 的自动扫描`" @change="toggle(sub)"><span class="track"><span class="thumb"></span></span></label></div><ActivityProgress v-if="scanState(sub)" :status="scanState(sub).status" :progress="scanState(sub).progress" :label="`${sub.nickname || sub.blogger_id} 扫描进度`"/><p v-if="sub.last_error" class="error-text scan-error">{{ sub.last_error }}</p><div class="sub-actions"><button class="btn btn-ghost btn-sm" :disabled="isScanning(sub)" @click="scanNow(sub)"><AppIcon name="scan" :size="18"/>{{ isScanning(sub)?'扫描中…':'立即扫描' }}</button><button class="btn btn-ghost btn-sm" :aria-expanded="expanded===sub.id" @click="expanded=expanded===sub.id?null:sub.id">{{ expanded===sub.id?'收起计划与记录':'计划与记录' }}</button><button class="btn btn-danger-ghost btn-sm" :disabled="isScanning(sub)" @click="remove(sub)">删除订阅</button></div><SchedulePanel v-if="expanded===sub.id" :sub="sub" @updated="refresh"/></article></div>
  </div>
</template>
<style scoped>
.add-card { position:relative; z-index:20; margin-bottom:24px; }.add-heading { display:flex; justify-content:space-between; align-items:center; gap:15px; margin-bottom:20px; }.add-heading h2 { font-size:17px; }.auth-status { display:flex; align-items:center; gap:10px; color:var(--text-2); font-size:11px; }.add-grid { display:grid; grid-template-columns:110px minmax(0,1.3fr) minmax(0,1fr) 100px; gap:14px; margin-bottom:20px; }.add-grid label { min-width:0; font-size:12px; color:var(--text-2); }.add-grid input,.add-grid select { margin-top:8px; font-size:13px; }.add-hint { color:var(--text-2); font-size:12px; line-height:1.7; margin-top:12px; }.search-field,.search-box { position:relative; }.search-drop { position:absolute; top:calc(100% + 6px); left:0; width:max(100%,300px); max-width:calc(100vw - 72px); max-height:330px; overflow:auto; background:#fbfcfd; border:1px solid var(--border); border-radius:14px; box-shadow:var(--shadow-card); padding:6px; z-index:40; }.drop-section { font-size:11px; padding:10px; }.drop-item { width:100%; display:flex; gap:10px; align-items:center; padding:10px; border:0; border-radius:10px; background:transparent; text-align:left; cursor:pointer; font-size:13px; }.drop-item.active,.drop-item:hover { background:#e7eff6; }.drop-item>span { min-width:0; flex:1; overflow-wrap:anywhere; }.drop-item small { display:block; color:var(--text-2); font-size:10px; margin-top:4px; }.drop-message { font-size:12px; padding:10px; line-height:1.7; }.cancel-search { position:absolute; bottom:-20px; right:0; border:0; background:transparent; font-size:10px; color:var(--blue); cursor:pointer; }.captcha-notice { padding:12px; font-size:12px; line-height:1.7; }.captcha-notice .btn { margin-top:10px; }.list-filters { display:flex; gap:12px; margin-bottom:20px; }.list-filters .input { flex:1; min-width:0; }.list-filters .select { width:140px; }.sub-list { display:flex; flex-direction:column; gap:15px; }.sub-card { padding:22px; }.sub-head { display:flex; align-items:center; gap:13px; }.sub-info { min-width:0; flex:1; }.sub-info h2 { display:flex; align-items:center; gap:8px; font-size:15px; overflow-wrap:anywhere; }.sub-info p { color:var(--text-2); font-size:11.5px; line-height:1.7; margin-top:3px; overflow-wrap:anywhere; }.sub-actions { display:flex; flex-wrap:wrap; gap:9px; margin-top:16px; }.error-text { color:#b13c30; font-size:12px; line-height:1.7; }.scan-error { margin-top:8px; }.empty p { margin-top:16px; }
@media(max-width:1150px){.add-grid { grid-template-columns:1fr 1fr; }}
@media(max-width:650px){.add-heading { align-items:flex-start; flex-direction:column; }.auth-status { flex-wrap:wrap; }.add-grid { grid-template-columns:1fr; }.list-filters { flex-wrap:wrap; }.list-filters .input { flex-basis:100%; }.list-filters .select { flex:1; width:auto; }.sub-card { padding:18px; }.search-drop { width:100%; min-width:0; }.sub-head { gap:9px; }.sub-info h2 { font-size:14px; } }
</style>
